module.exports={
    async redirects(){
        return [
            {
                source:"/userAccount",
                permanent:false,
                has:[
                    {
                        type:"cookie",
                        key:"__next_preview_data",
                        value:undefined
                    }
                ],
                destination:"/login"
            },
            {
                source:"/userAccount/licitaciones",
                permanent:false,
                has:[
                    {
                        type:"cookie",
                        key:"__next_preview_data",
                        value:undefined
                    }
                ],
                destination:"/login"
            },
            {
                source:"/userAccount/licitaciones/crearLicitacion",
                permanent:false,
                has:[
                    {
                        type:"cookie",
                        key:"__next_preview_data",
                        value:undefined
                    }
                ],
                destination:"/login"
            }
        ]
    },
    env:{
        API_REST:process.env.API_REST
    }
}